autoload -U compinit && compinit
autoload -U colors && colors

# History
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase
setopt inc_append_history  # Immediately append to the history file
setopt prompt_subst

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export GREP_COLOR='1;32'
export EDITOR="nvim"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

bindkey -e

# No flow control
stty -ixon -ixoff 2>/dev/null

# Resume nvim using ctrl+z instead of fg
foreground-vim() {
  fg %nvim # replace with your editor of choice
}
zle -N foreground-vim
bindkey '^Z' foreground-vim

### PROMPT
ruby_version() {
  echo -n "$(ruby -e 'print RUBY_VERSION')"
}

git_prompt() {
  local git_branch=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')

  if [[ -n "$git_branch" ]]; then
    if [[ -n $(git status --porcelain 2> /dev/null) ]]; then
      p="%{$fg[yellow]%}$git_branch \U2731%{$reset_color%}"
    else
      p="%{$fg[green]%}$git_branch \U2714%{$reset_color%}"
    fi
    echo "[$p]"
  fi
}

local user='%{$fg[white]%}%n%{$reset_color%}'
local host='%{$fg[white]%}%1m%{$reset_color%}'
local dir='%{$fg[cyan]%}%~%{$reset_color%}'
local ruby='%{$fg[red]%}$(ruby_version)%{$reset_color%}'
local git='$(git_prompt)%{$reset_color%}'
local prompt='%{$fg[green]%}\U276F %{$reset_color%}'

PROMPT=$(print "\n$dir $git\n$prompt")

precmd() {
  # iTerm tab titles. Sets the tab title to current dir
#  echo -ne "\e]1;${PWD##*/}\a"
}

# Change dir and list
function cl() {
  cd "$@" && ls -lh
}

### ALIAS
alias l="ls -lh"
alias la="ls -lah"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias du='du -kh'
alias df='df -kTh'
alias tlf="tail -f"
alias grep='grep --color=auto'
alias psg='ps aux | grep -v grep | grep'

alias e='nvim'
alias nv='nvim'

# Tmux
alias t='tmux'
alias tls='tmux ls'
alias tat='tmux at'
alias tka='tmux kill-session -a'
alias tns='tmux new -s'

# Git
alias g="git status -sb"
alias gd="git diff"
alias gbb="git branch"
alias push='git push'
alias gaa="git add --all"
alias gci="git commit -m"
alias gcm="git checkout master"
alias gum="git co master && git fetch && git reset --hard origin/master"
alias gumain="git co main && git fetch && git reset --hard origin/main"

# List local branches in a nice format
alias gb="git for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(color:cyan)%(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"
# Delete all local branches except main, master and develop
alias gbld="git for-each-ref --format '%(refname:short)' refs/heads | grep -v 'main\|master\|develop' | xargs git branch -D"
# Nice git grep
alias gg="git grep --break --heading --line-number"
# Nice git log
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
# Nice git log with graph
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Ruby on Rails
alias migrate="bin/rake db:migrate && bin/rake db:migrate RAILS_ENV=test"
alias remigrate="bin/rake db:migrate && bin/rake db:rollback && bin/rake db:migrate"
alias bi="bundle install"
alias bu="bundle update"
alias be="bundle exec"

# Docker
alias dk="docker"
alias dkc="docker compose"

# Python
alias pm="python manage.py"

# Reload ZSH config
alias reload='source ~/.zshrc'

### PATH
PATH="$HOME/.bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/opt/homebrew/bin:$PATH"
PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
PATH="/Library/TeX/texbin:$PATH"
export PATH

### EVAL section
if command -v rbenv &>/dev/null; then
  eval "$(rbenv init - zsh)"
fi

if command -v direnv &>/dev/null; then
  eval "$(direnv hook zsh)"
fi

if command -v brew &>/dev/null; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if command -v "fzf" &>/dev/null; then
  source <(fzf --zsh)
fi

### Local configuration
if [ -f ~/.zshrc.local ]; then
  . ~/.zshrc.local
fi
